org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.daemon.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8
kotlin.incremental=false
